CREATE TABLE Series (Title TEXT NOT NULL,
Series_geo_accession CHAR(20) NOT NULL,
Status TEXT NOT NULL,
Submission_date CHAR(20) NOT NULL,
Pubmed_id CHAR(20) NOT NULL,
Series_summary TEXT NOT NULL,
Series_overall_design TEXT NOT NULL,
Series_type TEXT NOT NULL,
Series_supplementary_file TEXT NOT NULL,
PRIMARY KEY(Series_geo_accession));

CREATE TABLE Contributors (Contributor_ID CHAR(20) NOT NULL,
Contributor_FirstName CHAR(20) NOT NULL,
Contributor_MiddleName CHAR(20) NOT NULL,
Contributor_LastName CHAR(20) NOT NULL,
PRIMARY KEY(Contributor_ID));


CREATE TABLE Series_Contributors (Series_geo_accession CHAR(20) NOT NULL,
Contributor_ID CHAR(20) NOT NULL,
FOREIGN KEY(Series_geo_accession) REFERENCES Series(Series_geo_accession),
FOREIGN KEY(Contributor_ID) REFERENCES Contributors(Contributor_ID));

CREATE TABLE Platforms (Platform_title TEXT NOT NULL,
    Platform_geo_accession CHAR(20) NOT NULL,
    Platform_technology TEXT NOT NULL,
    Platform_distribution TEXT NOT NULL,
    Platform_organism TEXT NOT NULL,
    Platform_taxid TEXT NOT NULL,
    Platform_manufacturer TEXT NOT NULL,
    PRIMARY KEY(Platform_geo_accession));

CREATE TABLE Series_Platforms (Series_geo_accession CHAR(20) NOT NULL,
    Platform_geo_accession CHAR(20) NOT NULL,
    FOREIGN KEY(Series_geo_accession) REFERENCES Series(Series_geo_accession),
    FOREIGN KEY(Platform_geo_accession) REFERENCES Platforms(Platform_geo_accession));

CREATE TABLE Samples (Title TEXT NOT NULL,
SampleID CHAR(20) NOT NULL,
Status TEXT NOT NULL,
Submission_date CHAR(20) NOT NULL,
Last_update_date CHAR(20) NOT NULL,
Samples_Type TEXT NOT NULL,
Channel_count INTEGER,
Source_name_ch1 TEXT NOT NULL,
Organism_ch1 TEXT NOT NULL,
Molecule_ch1 TEXT NOT NULL,
Label_ch1 TEXT NOT NULL,
Label_protocol_ch1 TEXT NOT NULL,
Taxid_ch1 TEXT NOT NULL,
Hyb_protocol TEXT NOT NULL,
Scan_protocol TEXT NOT NULL,
Platform_ID CHAR(20) NOT NULL,
Supplementary_file TEXT NOT NULL,
Data_row_count INTEGER,
PRIMARY KEY(SampleID));

CREATE TABLE Series_Samples (Series_geo_accession CHAR(20) NOT NULL,
SampleID CHAR(20) NOT NULL,
FOREIGN KEY(Series_geo_accession) REFERENCES Series(Series_geo_accession),
FOREIGN KEY(SampleID) REFERENCES Samples(SampleID));

CREATE TABLE GeneExpression (Gene_ID CHAR(20) NOT NULL,
Value INTEGER,
SampleID CHAR(20) NOT NULL,
PRIMARY KEY(Gene_ID),
FOREIGN KEY(SampleID) REFERENCES Samples(SampleID));

CREATE TABLE Ontology (Series_geo_accession CHAR(20) NOT NULL,
    Gene_ID CHAR(20) NOT NULL,
    Species CHAR(20) NOT NULL,
    Source CHAR(20) NOT NULL,
    Search_Key CHAR(20) NOT NULL,
    Transcript CHAR(20) NOT NULL,
    ILMN_Gene CHAR(20) NOT NULL,
    Source_Reference_ID CHAR(20) NOT NULL,
    RefSeq_ID CHAR(20) NOT NULL,
    Unigene_ID CHAR(20) NOT NULL,
    Entrez_Gene_ID CHAR(20) NOT NULL,
    GI CHAR(20) NOT NULL,
    Accession CHAR(20) NOT NULL,
    Symbol CHAR(20) NOT NULL,
    Protein_Product TEXT NOT NULL,
    Array_Address_Id CHAR(20) NOT NULL,
    Probe_Type CHAR(20) NOT NULL,
    Probe_Start TEXT NOT NULL,
    SEQUENCE TEXT NOT NULL,
    Chromosome TEXT NOT NULL,
    Probe_Chr_Orientation TEXT NOT NULL,
    Probe_Coordinates TEXT NOT NULL,
    Cytoband TEXT NOT NULL,
    Definition TEXT NOT NULL,
    Ontology_Component TEXT NOT NULL,
    Ontology_Process TEXT NOT NULL,
    Ontology_Function TEXT NOT NULL,
    Synonyms TEXT NOT NULL,
    GB_ACC TEXT NOT NULL,
    PRIMARY KEY(Gene_ID),
    FOREIGN KEY(Series_geo_accession) REFERENCES Series(Series_geo_accession));
