mysql vdam < DDLStatements;
mysql vdam < Series.csv.sql;
mysql vdam < Platforms.csv.sql;
mysql vdam < Samples.csv.sql;
mysql vdam < Contributors.csv.sql;
mysql vdam < Series_Contributors.csv.sql;
mysql vdam < Series_Platforms.csv.sql;
mysql vdam < Series_Samples.csv.sql;
mysql vdam < GeneExpression.csv.sql;
mysql vdam < Ontology.csv.sql
